USE [master]
GO
/****** Object:  Database [CHINAMOUPI]    Script Date: 08/11/2023 23:01:45 ******/
CREATE DATABASE [CHINAMOUPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CHINAMOUPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.CURLING\MSSQL\DATA\CHINAMOUPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CHINAMOUPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.CURLING\MSSQL\DATA\CHINAMOUPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CHINAMOUPI] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CHINAMOUPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CHINAMOUPI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET ARITHABORT OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CHINAMOUPI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CHINAMOUPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CHINAMOUPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CHINAMOUPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CHINAMOUPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CHINAMOUPI] SET  MULTI_USER 
GO
ALTER DATABASE [CHINAMOUPI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CHINAMOUPI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CHINAMOUPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CHINAMOUPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CHINAMOUPI] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CHINAMOUPI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CHINAMOUPI] SET QUERY_STORE = OFF
GO
USE [CHINAMOUPI]
GO
/****** Object:  Table [dbo].[cliente]    Script Date: 08/11/2023 23:01:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[cliente](
	[codigo] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[mesa]    Script Date: 08/11/2023 23:01:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[mesa](
	[codigo] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](30) NOT NULL,
	[Ocupada] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[mesamesero]    Script Date: 08/11/2023 23:01:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[mesamesero](
	[codigo] [int] IDENTITY(1,1) NOT NULL,
	[codigomesa] [int] NULL,
	[codigomesero] [int] NULL,
 CONSTRAINT [pk_codigomesamesero] PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[mesero]    Script Date: 08/11/2023 23:01:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[mesero](
	[codigo] [int] IDENTITY(100,1) NOT NULL,
	[NOMBRE] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[pedido]    Script Date: 08/11/2023 23:01:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[pedido](
	[codigo] [int] IDENTITY(1,1) NOT NULL,
	[codigomesa] [int] NULL,
	[codigomesero] [int] NULL,
	[codigocliente] [int] NULL,
	[pedido] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 08/11/2023 23:01:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[codigo] [int] IDENTITY(1,1) NOT NULL,
	[correo] [varchar](50) NOT NULL,
	[clave] [varchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[correo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[mesamesero]  WITH CHECK ADD  CONSTRAINT [fk_codigmesero] FOREIGN KEY([codigomesero])
REFERENCES [dbo].[mesero] ([codigo])
GO
ALTER TABLE [dbo].[mesamesero] CHECK CONSTRAINT [fk_codigmesero]
GO
ALTER TABLE [dbo].[mesamesero]  WITH CHECK ADD  CONSTRAINT [fk_codigomesa] FOREIGN KEY([codigomesa])
REFERENCES [dbo].[mesa] ([codigo])
GO
ALTER TABLE [dbo].[mesamesero] CHECK CONSTRAINT [fk_codigomesa]
GO
ALTER TABLE [dbo].[pedido]  WITH CHECK ADD  CONSTRAINT [fk_codigocliente2] FOREIGN KEY([codigocliente])
REFERENCES [dbo].[cliente] ([codigo])
GO
ALTER TABLE [dbo].[pedido] CHECK CONSTRAINT [fk_codigocliente2]
GO
ALTER TABLE [dbo].[pedido]  WITH CHECK ADD  CONSTRAINT [fk_codigomesa2] FOREIGN KEY([codigomesa])
REFERENCES [dbo].[mesa] ([codigo])
GO
ALTER TABLE [dbo].[pedido] CHECK CONSTRAINT [fk_codigomesa2]
GO
ALTER TABLE [dbo].[pedido]  WITH CHECK ADD  CONSTRAINT [fk_codigomesero2] FOREIGN KEY([codigomesero])
REFERENCES [dbo].[mesero] ([codigo])
GO
ALTER TABLE [dbo].[pedido] CHECK CONSTRAINT [fk_codigomesero2]
GO
USE [master]
GO
ALTER DATABASE [CHINAMOUPI] SET  READ_WRITE 
GO
